# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fd653ef815544c7a287143b2179fc35b5ce3c8b30c62d66603cfd7dc871762b78499b84ff7b6ec2b9f6f6345938ab324892446cd5aed36f893d6903158ddfaa

test:
  secret_key_base: 73c37289fb99669534589c51c793191173eb2b6fab01e12b40f60fe6acf53c0aa59de6692c73b3f26be855f9c9043512f85ad4098711fffc7ca5bb7a5eb4c4a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
